### ISSUE TITLE
Canceling login by closing browser isn't handled by CLI

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-cli-archived#100] opened 2021-05-05 06:59 UTC
**Describe the bug**
Using PowerShell 7.1.3, starting to login, and then closing the browser window leaves the CLI in a stuck state. ctrl+c won't work.

**To Reproduce**
1. Install CLI.
2. `mg login --scopes "group.read.all"`, a browser window will open.
3. Close the browser window.
4. Go to PowerShell window and try ctrl+c, the PowerShell session is stuck.
5. Wait a couple of minutes for PowerShell to provide the *Terminate batch job (Y/N)?* prompt.

**Expected behavior**
The CLI is called back from the closed browser window so that the CLI can fail fast and provide an actionable message to the user.
 
[AB#9276](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9276)

**Comment by jobala** [comment] 2021-05-06 07:19
@MIchaelMainer this issue is a duplicate of #63

**Closed as completed** 2021-05-06 23:50 UTC
Labels: bug
